Traceback (most recent call last):
  File "/dss/dsshome1/02/ra42vur3/prompt_tuning/capo/scripts/evaluate_prompts.py", line 90, in <module>
    run_experiment(args.experiment_path)
  File "/dss/dsshome1/02/ra42vur3/prompt_tuning/capo/scripts/evaluate_prompts.py", line 27, in run_experiment
    with open(f"{experiment_path}args.json", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results//rte/llama/CAPO/seed42benchmark_experiment_rte_llama_CAPO_4262e663a742481a2e0e0853b0a46d85dfaa7c59cc194a7536797c087df498662aargs.json'
